version: "3.8"

services:
  app:
    build: ./.docker/php
    image: nicepizza
    container_name: np_app_container
    volumes:
      - .:/home/nicepizza
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: np_db_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: np_adminer_container
    ports:
      - 8080:8080
    depends_on:
      - db

  mercure:
    image: dunglas/mercure
    container_name: np_mercure_container
    restart: unless-stopped
    ports:
      - 3000:80
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
